Add timeout to desktop-e2e-test-job-windows.yaml
containers/podman-desktop-e2e pull request #262
Opened 2024-10-25 10:11 UTC by danivilla9

Adds a 60-minute timeout to the 'Run Podman Desktop Playwright E2E tests' step so that the workflow can't get stuck. From previous executions this step should last between 35 and 45 minutes, so it should be enough time to run on a normal execution. Fixes #225.

2024-10-29 08:05 UTC, odockal commented
@danivilla9 Good. But I am thinking that applying more generous timeout for the whole job would be also good approach.
There are two timeout options to be set on either step or job level: https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes or https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idstepstimeout-minutes. So please add timeout, let's say 120 minutes on the level of the job. And we can apply the timeout to all jobs we have, please.

2024-10-29 08:05 UTC, odockal requested changes
please set the timeout to the job level, and to all jobs.

2024-10-29 09:12 UTC, danivilla9 commented
@odockal just added the job-level timeout to all e2e jobs, I figured that the build ones do not need one, being as fast as they are. I could add a shorter timeout in them if you think it's relevant.

2024-10-30 07:38 UTC, odockal approved these changes

2024-10-30 07:38 UTC, merged

2024-10-30 07:39 UTC, odockal commented
@danivilla9 No need to add them for build job. thanks!