chore: switch to podman setup.exe
containers/podman-desktop-e2e pull request #264
Opened 2024-10-25 11:25 UTC by danivilla9

Switches the previous installation of podman (zip archive) to using the setup.exe version. Fixes #240

2024-10-25 12:13 UTC, benoitf reviewed
question: how do you determine the version of podman to use ?

podman desktop is using the v5.2.5
https://github.com/containers/podman-desktop/blob/main/extensions/podman/packages/extension/src/podman5.json

2024-10-28 11:28 UTC, danivilla9 commented
> question: how do you define the version of podman to use ? here I see 5.2.4, before 5.0.3 so it seems for both not in sync with either the latest from podman or the one podman desktop is using
> 
> podman desktop is using the v5.2.5 https://github.com/containers/podman-desktop/blob/main/extensions/podman/packages/extension/src/podman5.json

I used the previous existing version used on other yaml files, I did not realize that it wasn't the most recent one. The older version that was being used earlier (5.0.3) probably was forgotten to be updated as time went on, unless I'm mistaken.

I've updated all instances to v5.2.5 for consistency

2024-10-29 08:15 UTC, odockal commented
Regarding inputs. This does not really matters, since the parameter is only used when run on event `workflow_dispatch`. What we really needs it to use particular podman version based on the context of the job.

In [this job](https://github.com/containers/podman-desktop-e2e/blob/main/.github/workflows/podman-desktop-e2e-windows.yaml) we are installing the podman from podman-desktop, so no need to specify any particular podman version.

In [job](https://github.com/containers/podman-desktop-e2e/blob/main/.github/workflows/podman-desktop-e2e-nightly-windows-wsl.yaml) where we test podman-nightly installed from the nightly CI builds we might just set a new version in input parameter, but when run on nightly base on schedule, the latest podman remote version is used.

Where we really need to consider using latest podman that is available or defined by podman-desktop is [this one](https://github.com/containers/podman-desktop-e2e/blob/main/.github/workflows/podman-desktop-e2e-nightly-windows-hyperv.yaml) where we want to use setup.exe podman version as defined in podman-desktop because there is no setup.exe from the podman nightly CI builds, so we need to add a code to define version like in [bootc](https://github.com/containers/podman-desktop-extension-bootc/blob/main/.github/workflows/bootc-e2e-nightly-windows.yaml#L95) and use in when job is triggered  on schedule. Again we can use some particular latest version in input but that does not really matter (although is nice to have latest there).

On the missing two jobs, we just update input default value. that is fine since the job are only run as `workflow_dispatch`. thus only using user's set params.

2024-10-30 07:33 UTC, odockal commented on .github/workflows/podman-desktop-e2e-nightly-windows-hyperv.yaml
> +        echo "PODMAN_VERSION=${{ github.event.inputs.podman_version || env.DEFAULT_VERSION }}" >> $GITHUB_ENV
the version env. var. is not being used in the podman image. please remove.

2024-10-30 07:33 UTC, odockal commented on .github/workflows/podman-desktop-e2e-nightly-windows-hyperv.yaml
> +              -version ${{ env.PODMAN_VERSION }} \
version param not used anymore. please remove.

2024-10-30 07:33 UTC, odockal requested changes
Good changes, except version param that is not used anymore. the remote url is the important one.

2024-10-30 08:20 UTC, odockal approved these changes

2024-10-30 08:21 UTC, merged